"""
self_improve_v2.py
------------------
Reads the latest backtest results, generates a structured reflection,
and appends it to trading_memory.md for the Portfolio Manager to use.

Usage:
    python demo/self_improve_v2.py
    python demo/self_improve_v2.py --backtest-file path/to/backtest.json
"""

import sys
import json
import logging
import argparse
from datetime import date, datetime
from pathlib import Path
from typing import Optional

import yaml
from dotenv import load_dotenv

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))
load_dotenv(REPO_ROOT / ".env")

CONFIG_PATH = Path(__file__).parent / "config_v2.yaml"
with open(CONFIG_PATH) as f:
    CFG = yaml.safe_load(f)

logging.basicConfig(
    level=getattr(logging, CFG["logging"]["level"]),
    format="%(asctime)s  %(levelname)-8s  %(name)s  %(message)s",
    handlers=[logging.StreamHandler(sys.stdout)],
)
logger = logging.getLogger("self_improve")

DECISION_LOG_DIR = REPO_ROOT / CFG["dashboard"]["decision_log_dir"]
MEMORY_FILE = REPO_ROOT / CFG["self_improve"]["memory_file"]
MIN_TRADES = CFG["self_improve"]["min_trades_for_reflection"]
MAX_LEN = CFG["self_improve"]["max_reflection_length"]


def find_latest_backtest() -> Optional[Path]:
    candidates = sorted(DECISION_LOG_DIR.glob("backtest_*.json"), reverse=True)
    return candidates[0] if candidates else None


def load_backtest(path: Path) -> dict:
    with open(path) as f:
        return json.load(f)


def _format_pct(val: float) -> str:
    return f"{val * 100:+.2f}%"


def generate_reflection(bt: dict) -> str:
    metrics = bt.get("metrics", {})
    ticker_stats = bt.get("ticker_stats", {})
    trades_list = bt.get("trades", [])
    run_date = bt.get("run_date", date.today().isoformat())

    closed = [t for t in trades_list if t.get("is_closed")]
    if len(closed) < MIN_TRADES:
        logger.info(
            f"Only {len(closed)} closed trades - minimum {MIN_TRADES} required. "
            "Skipping reflection."
        )
        return ""

    sorted_tickers = sorted(
        ticker_stats.items(),
        key=lambda x: x[1].get("total_return", 0),
        reverse=True,
    )
    top3 = sorted_tickers[:3]
    worst3 = sorted_tickers[-3:]

    closed_df_rows = [
        t for t in closed
        if t.get("trade_return") is not None and t.get("action") != "HOLD"
    ]
    buy_returns = [t["trade_return"] for t in closed_df_rows if t["action"] == "BUY"]
    sell_returns = [t["trade_return"] for t in closed_df_rows if t["action"] == "SELL"]

    buy_hr = sum(1 for r in buy_returns if r > 0) / len(buy_returns) if buy_returns else 0
    sell_hr = sum(1 for r in sell_returns if r > 0) / len(sell_returns) if sell_returns else 0
    buy_avg = sum(buy_returns) / len(buy_returns) if buy_returns else 0
    sell_avg = sum(sell_returns) / len(sell_returns) if sell_returns else 0

    lines = [
        f"",
        f"---",
        f"## Performance Reflection - {run_date}",
        f"*Auto-generated by self_improve_v2.py after backtest cycle*",
        f"",
        f"### Summary Metrics ({bt.get('lookback_days', '?')}d lookback, "
        f"{bt.get('holding_period_days', '?')}d holding period)",
        f"| Metric | Value |",
        f"|--------|-------|",
        f"| Closed Trades | {metrics.get('closed_trades', 0)} |",
        f"| Hit Rate | {metrics.get('hit_rate', 0)*100:.1f}% |",
        f"| Sharpe Ratio | {metrics.get('sharpe_ratio', 0):.3f} |",
        f"| Alpha vs {bt.get('benchmark', 'SPY')} | {_format_pct(metrics.get('alpha_vs_benchmark', 0))} |",
        f"| Total PnL | {_format_pct(metrics.get('total_pnl_pct', 0))} |",
        f"| Avg Trade Return | {_format_pct(metrics.get('avg_trade_return_pct', 0))} |",
        f"",
        f"### Action Analysis",
        f"- BUY signals: {len(buy_returns)} trades, hit rate {buy_hr*100:.0f}%, "
        f"avg return {_format_pct(buy_avg)}",
        f"- SELL signals: {len(sell_returns)} trades, hit rate {sell_hr*100:.0f}%, "
        f"avg return {_format_pct(sell_avg)}",
        f"",
        f"### Top Performing Tickers",
    ]

    for ticker, stats in top3:
        lines.append(
            f"- {ticker}: {_format_pct(stats['total_return'])} total, "
            f"{stats['hit_rate']*100:.0f}% hit rate, "
            f"{stats['decisions']} decisions"
        )

    lines += ["", "### Underperforming Tickers"]
    for ticker, stats in reversed(worst3):
        lines.append(
            f"- {ticker}: {_format_pct(stats['total_return'])} total, "
            f"{stats['hit_rate']*100:.0f}% hit rate"
        )

    lines += ["", "### Lessons & Adjustments for Portfolio Manager"]

    if metrics.get("sharpe_ratio", 0) < 0.5:
        lines.append(
            "- WARNING: Low Sharpe ratio. Increase confidence threshold or "
            "wait for stronger conviction before acting."
        )

    if metrics.get("hit_rate", 0) < 0.5:
        lines.append(
            "- WARNING: Below 50% hit rate. Consider HOLD as default unless "
            "confidence > 0.75."
        )

    if buy_hr > sell_hr + 0.15:
        lines.append(
            "- BUY signals are significantly more accurate than SELL. "
            "Be more aggressive on BUY setups."
        )
    elif sell_hr > buy_hr + 0.15:
        lines.append(
            "- SELL signals outperform BUY signals in this period. "
            "Consider short-bias positioning."
        )

    if metrics.get("alpha_vs_benchmark", 0) < 0:
        lines.append(
            "- WARNING: Negative alpha vs benchmark. Question whether active "
            "trading is adding value vs passive index exposure."
        )

    if top3:
        best_ticker = top3[0][0]
        lines.append(
            f"- {best_ticker} has been the strongest signal. "
            "Increase conviction for this ticker on next cycle."
        )

    lines += ["", "*End of reflection*", ""]

    reflection = "\n".join(lines)
    return reflection[:MAX_LEN]


def append_to_memory(reflection: str) -> None:
    MEMORY_FILE.parent.mkdir(parents=True, exist_ok=True)

    if not MEMORY_FILE.exists():
        MEMORY_FILE.write_text(
            "# Trading Memory\n\n"
            "*This file is automatically updated by self_improve_v2.py after each "
            "backtest cycle. The Portfolio Manager reads this file to inform "
            "future trading decisions.*\n",
            encoding="utf-8",
        )
        logger.info(f"Created new trading_memory.md at {MEMORY_FILE}")

    with open(MEMORY_FILE, "a", encoding="utf-8") as f:
        f.write(reflection)
        f.write("\n")

    logger.info(f"Appended reflection to {MEMORY_FILE}")


def run(backtest_file: Optional[str] = None) -> None:
    if backtest_file:
        bt_path = Path(backtest_file)
    else:
        bt_path = find_latest_backtest()

    if bt_path is None or not bt_path.exists():
        logger.warning(
            "No backtest file found. Run `python demo/backtest_v2.py` first."
        )
        return

    logger.info(f"Loading backtest results from {bt_path} ...")
    bt = load_backtest(bt_path)

    reflection = generate_reflection(bt)
    if not reflection:
        return

    append_to_memory(reflection)
    logger.info("Self-improvement cycle complete.")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generate self-improvement reflection")
    parser.add_argument("--backtest-file", type=str, default=None)
    args = parser.parse_args()
    run(backtest_file=args.backtest_file)
